# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev3+g5d4d652.d20230802'
__version_tuple__ = version_tuple = (0, 1, 'dev3', 'g5d4d652.d20230802')
